### ISSUE TITLE
how to convert grib2 to json

### ISSUE THREAD

**Issue by bigbeef** [philippphb/GRIB2Tools#8]
like this tool:https://github.com/cambecc/grib2json

**Comment by philippphb** [comment]
Hello @bigbeef, thank you for your comment, could you please specify what the issue you are facing is?

**Comment by philippphb** [comment]
Hi @bigbeef, the functionality is not yet implemented. 

But you can use the library to read and decode a GRIB file. Then it's very easy to access all meta data and the data of the GRIB file, so that you can just create a JSON stream from this.

If you decided to do this, and you want to contribute to the lib, and provide your code to extend the lib, would be great! Let me know then
